sudo: required

dist: trusty

language: node_js
node_js:
  - "node"

addons:
  sonarcloud: true
  apt:
    sources:
     - sourceline: 'deb http://download.mono-project.com/repo/ubuntu trusty main'
       key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF'
    packages:
     - mono-complete


jdk:
  - oraclejdk8

git:
  depth: false

before_install: 
  - wget -O os.deb http://oscript.io/downloads/night-build/deb?bitness=x64
  - sudo dpkg -i os.deb; sudo apt install -f
  - oscript
  # - sudo opm update opm
  - sudo opm install strings
  - sudo opm install oscript-config

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - npm install
  - npm run vscode:prepublish

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - export SONARQUBE_SKIPPED=false
  - npm test --silent
  - tslint -t json -o report.json --project . --force
  - ./sonar.sh 

after_script:
  - bash <(curl -s https://codecov.io/bash)
