sudo: required

dist: trusty

language: node_js
node_js:
  - "node"

addons:
  sonarqube: true

jdk:
  - oraclejdk8

before_install: 
  - wget -O os.deb https://files.gitter.im/EvilBeaver/OneScript/VreX/onescript-engine_1.0.17_all.deb
  - sudo apt-get install mono-complete mono-devel
  - sudo dpkg -i os.deb; sudo apt install -f
  - oscript
  # - sudo opm update opm
  - sudo opm install strings
  - sudo opm install oscript-config

install: 
  - npm install
  - npm run vscode:prepublish

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - export SONARQUBE_SKIPPED=false
  - ./travis.sh 

after_script:
  - bash <(curl -s https://codecov.io/bash)
