name: Publish package to VSCode Marketplace

on:
    release:
        types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Upload vsce to release
        uses: AButler/upload-release-assets@v1.0
        with:
            files: './.*.vsix'
            repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
